language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build
  - rm _site/pages/*/*/README.html
  - bundle exec htmlproofer ./_site --only-4xx --disable-external --check-html --allow-hash-href --assume-extension
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
