language: ruby
rvm:
  - 2.6
script:
  - bundle exec jekyll build | tee jekyll_build.log
  - grep -v "Build Warning:" jekyll_build.log
  - find _site/pages/ -name "README.html" -type f -delete
  - find _site/pages/ -name "CHANGELOG.html" -type f -delete
  - bundle exec htmlproofer ./_site --only-4xx --disable-external --check-html --allow-hash-href --assume-extension
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
